version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: test-database
    environment:
      MYSQL_ROOT_PASSWORD: test
      TZ: Asia/Seoul
    ports:
      - "13333:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:13333/test-db

