version: '3.8'

services:
  dev-db:
    image: mysql:8.0
    container_name: dev-db
    environment:
      MYSQL_ROOT_PASSWORD: dev
      TZ: Asia/Seoul
    ports:
      - "13333:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  test-db:
    image: mysql:8.0
    container_name: test-db
    environment:
      MYSQL_ROOT_PASSWORD: test
      TZ: Asia/Seoul
    ports:
      - "13336:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
